server {
    listen 80;
    server_name ec2-13-48-195-204.eu-north-1.compute.amazonaws.com; # Replace with your actual domain

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri; # Force redirect to HTTPS
    }
}
