events {}

http {
    # Rate Limiting: Max 10 requests per second from one IP
    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s;

    server {
        listen 80;
	server_name ec2-13-48-195-204.eu-north-1.compute.amazonaws.com;
        gzip on;
        gzip_types text/plain text/css application/json;

        location / {
            limit_req { zone=mylimit burst=20 nodelay; }
            proxy_pass http://backend:8000; # Points to your Docker container
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
